		<p><a href="ajoutPublic.php">Ajout de personne</a></p>
		<p><a href="ajoutElement.php" >Ajout élément</a></p>
		<p><a href="modificationEpoque.php">Modification époque</a></p>
		<p><a href="modificationLieu.php">Modification lieu</a></p>
		<p><a href="modificationTheme.php">Modification theme</a></p>
		<p><a href="modificationType.php">Modification type</a></p>
		<p><a href="suppressionEpoque.php">Suppression époque</a></p>
		<p><a href="suppressionLieu.php">Suppression lieu</a></p>
		<p><a href="suppressionTheme.php">Suppression Thème</a></p>
		<p><a href="suppressionType.php">Suppression Type</a></p>